"""changed expiry date to expiry time

Revision ID: 276187366b72
Revises: 636f0c03130f
Create Date: 2026-04-09 00:32:52.944812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '276187366b72'
down_revision: Union[str, Sequence[str], None] = '636f0c03130f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expiry_time', sa.DateTime(), nullable=True))
    op.drop_column('tasks', 'expiry_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expiry_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'expiry_time')
    # ### end Alembic commands ###
