"""add expiryTime column

Revision ID: 636f0c03130f
Revises: c2ff66a00b4c
Create Date: 2026-04-09 00:30:30.313143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636f0c03130f'
down_revision: Union[str, Sequence[str], None] = 'c2ff66a00b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'expiry_date')
    # ### end Alembic commands ###
