"""add task completion table

Revision ID: 9df24c4fd4e9
Revises: e7fd02c2974b
Create Date: 2026-04-04 14:03:34.156832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df24c4fd4e9'
down_revision: Union[str, Sequence[str], None] = 'e7fd02c2974b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_completion_date'), 'task_completions', ['completion_date'], unique=False)
    op.create_index(op.f('ix_task_completions_id'), 'task_completions', ['id'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completion_date'), table_name='task_completions')
    op.drop_table('task_completions')
    # ### end Alembic commands ###
