"""added is_deleted

Revision ID: c2ff66a00b4c
Revises: 9df24c4fd4e9
Create Date: 2026-04-04 17:29:53.066022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ff66a00b4c'
down_revision: Union[str, Sequence[str], None] = '9df24c4fd4e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_completions', 'is_deleted')
    # ### end Alembic commands ###
