"""added belongs_to_date column

Revision ID: e7fd02c2974b
Revises: e3d8ef0fedbe
Create Date: 2026-04-03 16:25:40.294679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fd02c2974b'
down_revision: Union[str, Sequence[str], None] = 'e3d8ef0fedbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('belongs_to_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_belongs_to_date'), 'tasks', ['belongs_to_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_belongs_to_date'), table_name='tasks')
    op.drop_column('tasks', 'belongs_to_date')
    # ### end Alembic commands ###
